// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igvtuaggwcdgizbchlpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlndnR1YWdnd2NkZ2l6YmNobHBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3ODU4ODUsImV4cCI6MjA2NDM2MTg4NX0.usb0oy_fOLoFyifMADvSkI9EL6aN5SDKDqYx1RbALUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);